In [28]:
import pandas as pd
import numpy as np

# Define the initial data
human_evals_data = {
    "Metric": [
        "Technical Quality (mean)",
        "Conversational Score (mean)",
        "Technical Quality Std. Dev.",
        "Conversational Score Std. Dev."
    ],
    "Human": [6.88, 6.05, 1.942, 1.783],
    "AI": [8.34, 8.04, 0.906, 1.114]
}

# Create the DataFrame
human_evals_df = pd.DataFrame(human_evals_data)
human_evals_df.head()

                           Metric  Human     AI
0        Technical Quality (mean)  6.880  8.340
1     Conversational Score (mean)  6.050  8.040
2     Technical Quality Std. Dev.  1.942  0.906
3  Conversational Score Std. Dev.  1.783  1.114

In [29]:
# Sample size
n_70 = 70

# Calculate standard errors for n=70
human_evals_human_errors = [round(human_evals_df.loc[2, "Human"] / np.sqrt(n_70), 3), round(human_evals_df.loc[3, "Human"] / np.sqrt(n_70), 3)]
human_evals_ai_errors = [round(human_evals_df.loc[2, "AI"] / np.sqrt(n_70), 3), round(human_evals_df.loc[3, "AI"] / np.sqrt(n_70), 3)]
human_evals_diff_errors = [
    round(np.sqrt((human_evals_human_errors[0])**2 + (human_evals_ai_errors[0])**2), 3),
    round(np.sqrt((human_evals_human_errors[1])**2 + (human_evals_ai_errors[1])**2), 3)
]

human_evals_standard_errors = {
    "Metric": [
        "Technical Quality (mean)",
        "Conversational Score (mean)"
    ],
    "Human (Control)": human_evals_human_errors,
    "AI (Treatment)": human_evals_ai_errors,
    "Difference (AI - Human)": human_evals_diff_errors
}

# Create standard error DataFrame
human_evals_df_standard_errors = pd.DataFrame(human_evals_standard_errors)

# Display the DataFrame
human_evals_df_standard_errors.head()

,Metric,Human (Control),AI (Treatment),Difference (AI - Human)
0,Technical Quality (mean),0.232,0.108,0.256
1,Conversational Score (mean),0.213,0.133,0.251

In [30]:

# Clubbed DataFrame with values and standard errors for n=70
final_human_evals_data = {
    "Metric": [
        "Technical Quality (mean)",
        "Conversational Score (mean)"
    ],
    "Human (Control)": [f"{human_evals_df.loc[0, 'Human']} ({human_evals_human_errors[0]})", f"{human_evals_df.loc[1, 'Human']} ({human_evals_human_errors[1]})"],
    "AI (Treatment)": [f"{human_evals_df.loc[0, 'AI']} ({human_evals_ai_errors[0]})", f"{human_evals_df.loc[1, 'AI']} ({human_evals_ai_errors[1]})"],
    "Difference (AI - Human)": [
        f"{round(human_evals_df.loc[0, 'AI'] - human_evals_df.loc[0, 'Human'], 2)} ({human_evals_diff_errors[0]})",
        f"{round(human_evals_df.loc[1, 'AI'] - human_evals_df.loc[1, 'Human'], 2)} ({human_evals_diff_errors[1]})"
    ]
}

# Create the final DataFrame for n=70
human_evals_df_final = pd.DataFrame(final_human_evals_data)

human_evals_df_final.head()

,Metric,Human (Control),AI (Treatment),Difference (AI - Human)
0,Technical Quality (mean),6.88 (0.232),8.34 (0.108),1.46 (0.256)
1,Conversational Score (mean),6.05 (0.213),8.04 (0.133),1.99 (0.251)

In [31]:

# Define the new data for n=575
llm_as_judge_data = {
    "Metric": [
        "Technical Quality (mean)",
        "Conversational Score (mean)",
        "Technical Quality Std. Dev.",
        "Conversational Score Std. Dev."
    ],
    "Human": [7.85, 5.41, 0.784, 1.254],
    "AI": [8.37, 7.8, 0.453, 0.475]
}

# Create the DataFrame for n=575
llm_as_judge_df = pd.DataFrame(llm_as_judge_data)

llm_as_judge_df.head()

                           Metric  Human     AI
0        Technical Quality (mean)  7.850  8.370
1     Conversational Score (mean)  5.410  7.800
2     Technical Quality Std. Dev.  0.784  0.453
3  Conversational Score Std. Dev.  1.254  0.475

In [32]:
# Sample size
n_575 = 575

# Calculate standard errors for n=575
llm_as_judge_human_errors = [round(llm_as_judge_df.loc[2, "Human"] / np.sqrt(n_575), 3), round(llm_as_judge_df.loc[3, "Human"] / np.sqrt(n_575), 3)]
llm_as_judge_ai_errors = [round(llm_as_judge_df.loc[2, "AI"] / np.sqrt(n_575), 3), round(llm_as_judge_df.loc[3, "AI"] / np.sqrt(n_575), 3)]
llm_as_judge_diff_errors = [
    round(np.sqrt((llm_as_judge_human_errors[0])**2 + (llm_as_judge_ai_errors[0])**2), 3),
    round(np.sqrt((llm_as_judge_human_errors[1])**2 + (llm_as_judge_ai_errors[1])**2), 3)
]

llm_as_judge_standard_errors = {
    "Metric": [
        "Technical Quality (mean)",
        "Conversational Score (mean)"
    ],
    "Human (Control)": llm_as_judge_human_errors,
    "AI (Treatment)": llm_as_judge_ai_errors,
    "Difference (AI - Human)": llm_as_judge_diff_errors
}

# Create standard error DataFrame
llm_as_judge_df_standard_errors = pd.DataFrame(llm_as_judge_standard_errors)

# Display the DataFrame
llm_as_judge_df_standard_errors.head()

,Metric,Human (Control),AI (Treatment),Difference (AI - Human)
0,Technical Quality (mean),0.033,0.019,0.038
1,Conversational Score (mean),0.052,0.020,0.056

In [33]:

# Clubbed DataFrame with values and standard errors for n=575
llm_as_judge_final_data = {
    "Metric": [
        "Technical Quality (mean)",
        "Conversational Score (mean)"
    ],
    "Human (Control)": [f"{llm_as_judge_df.loc[0, 'Human']} ({llm_as_judge_human_errors[0]})", f"{llm_as_judge_df.loc[1, 'Human']} ({llm_as_judge_human_errors[1]})"],
    "AI (Treatment)": [f"{llm_as_judge_df.loc[0, 'AI']} ({llm_as_judge_ai_errors[0]})", f"{llm_as_judge_df.loc[1, 'AI']} ({llm_as_judge_ai_errors[1]})"],
    "Difference (AI - Human)": [
        f"{round(llm_as_judge_df.loc[0, 'AI'] - llm_as_judge_df.loc[0, 'Human'], 2)} ({llm_as_judge_ai_errors[0]})",
        f"{round(llm_as_judge_df.loc[1, 'AI'] - llm_as_judge_df.loc[1, 'Human'], 2)} ({llm_as_judge_ai_errors[1]})"
    ]
}

# Create the final DataFrame for n=575
llm_as_judge_df_final = pd.DataFrame(llm_as_judge_final_data)

# Display the final DataFrames
llm_as_judge_df_final.head()

,Metric,Human (Control),AI (Treatment),Difference (AI - Human)
0,Technical Quality (mean),7.85 (0.033),8.37 (0.019),0.52 (0.019)
1,Conversational Score (mean),5.41 (0.052),7.8 (0.02),2.39 (0.02)

In [34]:
from IPython.display import display

print("STANDARD ERROR CALCULATION FOR HUMAL EVALS METRICS")
display(human_evals_df.head())
display(human_evals_df_standard_errors.head())
display(human_evals_df_final.head())

print("\n\n\nSTANDARD ERROR CALCULATION FOR LLM AS JUDGE METRICS")
display(llm_as_judge_df.head())
display(llm_as_judge_df_standard_errors.head())
display(llm_as_judge_df_final.head())

STANDARD ERROR CALCULATION FOR HUMAL EVALS METRICS

                           Metric  Human     AI
0        Technical Quality (mean)  6.880  8.340
1     Conversational Score (mean)  6.050  8.040
2     Technical Quality Std. Dev.  1.942  0.906
3  Conversational Score Std. Dev.  1.783  1.114

,Metric,Human (Control),AI (Treatment),Difference (AI - Human)
0,Technical Quality (mean),0.232,0.108,0.256
1,Conversational Score (mean),0.213,0.133,0.251

,Metric,Human (Control),AI (Treatment),Difference (AI - Human)
0,Technical Quality (mean),6.88 (0.232),8.34 (0.108),1.46 (0.256)
1,Conversational Score (mean),6.05 (0.213),8.04 (0.133),1.99 (0.251)

STANDARD ERROR CALCULATION FOR LLM AS JUDGE METRICS

                           Metric  Human     AI
0        Technical Quality (mean)  7.850  8.370
1     Conversational Score (mean)  5.410  7.800
2     Technical Quality Std. Dev.  0.784  0.453
3  Conversational Score Std. Dev.  1.254  0.475

,Metric,Human (Control),AI (Treatment),Difference (AI - Human)
0,Technical Quality (mean),0.033,0.019,0.038
1,Conversational Score (mean),0.052,0.020,0.056

,Metric,Human (Control),AI (Treatment),Difference (AI - Human)
0,Technical Quality (mean),7.85 (0.033),8.37 (0.019),0.52 (0.019)
1,Conversational Score (mean),5.41 (0.052),7.8 (0.02),2.39 (0.02)